name: Build
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          curl https://www.sourcemod.net/smdrop/1.11/$(curl --silent https://www.sourcemod.net/smdrop/1.11/sourcemod-latest-linux) -o sourcemod.tar.gz
          tar -xf sourcemod.tar.gz
          addons/sourcemod/scripting/spcomp64 forcecmd.sp
      - uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: ./forcecmd.smx
